import java.util.ArrayList;

public class JobDescription {
    String title;
    ArrayList<String> skillQualification;
    ArrayList<String> educationQualification;
    ArrayList<String> experienceQualification;

    // keywords

//    education_keywords = [
//            "Bachelor's Degree",
//            "Master's Degree",
//            "Doctorate",
//            "PhD",
//            "Associate Degree",
//            "High School Diploma",
//            "GED",
//            "Undergraduate",
//            "Postgraduate",
//            "MBA",
//            "BSc",
//            "BA",
//            "MSc",
//            "MS",
//            "MA",
//            "BS",
//            "Diploma",
//            "Certificate",
//            "Bootcamp",
//            "Online Course",
//            "Coursera",
//            "edX",
//            "Udemy",
//            "Google Certification",
//            "AWS Certified",
//            "Data Science Certificate",
//            "Cybersecurity Certification",
//            "Computer Science",
//            "Information Technology",
//            "Engineering",
//            "Mathematics",
//            "Statistics",
//            "Physics",
//            "Artificial Intelligence",
//            "Machine Learning",
//            "Business Administration",
//            "Marketing",
//            "Finance",
//            "Economics"
//            ]

//    skill_keywords = [
//            "Python",
//            "Java",
//            "C++",
//            "C#",
//            "JavaScript",
//            "TypeScript",
//            "HTML",
//            "CSS",
//            "SQL",
//            "NoSQL",
//            "MongoDB",
//            "PostgreSQL",
//            "MySQL",
//            "React",
//            "Angular",
//            "Vue.js",
//            "Node.js",
//            "Django",
//            "Flask",
//            "Spring Boot",
//            "Kubernetes",
//            "Docker",
//            "AWS",
//            "Azure",
//            "GCP",
//            "TensorFlow",
//            "PyTorch",
//            "Scikit-learn",
//            "Pandas",
//            "NumPy",
//            "Matplotlib",
//            "Power BI",
//            "Tableau",
//            "Data Analysis",
//            "Data Visualization",
//            "Machine Learning",
//            "Deep Learning",
//            "NLP",
//            "Computer Vision",
//            "DevOps",
//            "Agile",
//            "Scrum",
//            "CI/CD",
//            "Linux",
//            "Git",
//            "Version Control",
//            "REST API",
//            "GraphQL",
//            "Microservices",
//            "Cloud Computing",
//            "Project Management",
//            "Communication",
//            "Leadership",
//            "Problem Solving",
//            "Critical Thinking"
//            ]

//    experience_keywords = [
//            "Internship",
//            "Full-time",
//            "Part-time",
//            "Contract",
//            "Freelance",
//            "Remote",
//            "On-site",
//            "Project Management",
//            "Team Leadership",
//            "Mentoring",
//            "Technical Lead",
//            "Software Engineer",
//            "Data Scientist",
//            "Machine Learning Engineer",
//            "DevOps Engineer",
//            "Backend Developer",
//            "Frontend Developer",
//            "System Architect",
//            "IT Support",
//            "Network Engineer",
//            "Product Manager",
//            "Business Analyst",
//            "Research Assistant",
//            "Teaching Assistant",
//            "Project Coordinator",
//            "Consultant",
//            "Process Improvement",
//            "Automation",
//            "Performance Optimization",
//            "Deployment",
//            "Testing",
//            "Debugging",
//            "System Design",
//            "Code Review",
//            "Cross-functional Collaboration",
//            "Stakeholder Communication",
//            "Agile Development",
//            "Sprint Planning",
//            "Technical Documentation",
//            "Client Interaction",
//            "User Research",
//            "Prototyping"
//            ]


}
